# This file was generated by GoReleaser. DO NOT EDIT.
cask "greenlight" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f609cd2b8b810131d46ac231b6b7d124e9f22ab3ca13c646370c5d334ee36920"
      url "https://github.com/RevylAI/greenlight/releases/download/v#{version}/greenlight_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ccba1ab1608f80f9a89e7a7d092937116a63273ac9be9310ec95b696de43b5b"
      url "https://github.com/RevylAI/greenlight/releases/download/v#{version}/greenlight_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e075a588a3b7968de903e53d904cabc983904dadb76906cb5aa149acf07dfff"
      url "https://github.com/RevylAI/greenlight/releases/download/v#{version}/greenlight_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66a2a1b8066bf468d4e352fa97492022d3596d69f45d6aa0b84c26aedb332d80"
      url "https://github.com/RevylAI/greenlight/releases/download/v#{version}/greenlight_#{version}_linux_arm64.tar.gz"
    end
  end

  name "greenlight"
  desc "WRITE PATH TEST - should be reverted by the workflow"
  homepage "https://github.com/RevylAI/greenlight"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "greenlight"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/greenlight"]
    end
  end

  # No zap stanza required

end
