#!/usr/bin/env python3
"""Regenerate Casks/greenlight.rb from the latest published greenlight release.

The greenlight release workflow is supposed to push the cask here itself, using
a HOMEBREW_TAP_TOKEN PAT, because a workflow's built-in GITHUB_TOKEN cannot
write to another repository. That secret has never existed, so the v0.2.0
release published its binaries and then failed on the cask step, leaving this
tap pointing at v0.1.0.

This inverts the direction. Reading a public repository's releases needs no
credentials at all, and a workflow *can* write to its own repository, so the tap
updates itself and no cross-repo token is involved.

Output is kept byte-identical to what GoReleaser's homebrew_casks template
produces, so if the PAT is ever configured the two agree and neither reverts the
other.

stdlib only: this runs on a bare runner with no pip install step.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = "RevylAI/greenlight"
CASK = Path("Casks/greenlight.rb")

# The four archives GoReleaser builds, in the order its template emits them.
TARGETS = [
    ("on_macos", "on_intel", "darwin_amd64"),
    ("on_macos", "on_arm", "darwin_arm64"),
    ("on_linux", "on_intel", "linux_amd64"),
    ("on_linux", "on_arm", "linux_arm64"),
]

FALLBACK_DESC = "Pre-submission compliance scanner for the Apple App Store and Google Play"


def get(url: str, raw: bool = False):
    req = urllib.request.Request(url, headers={"User-Agent": "revylai-homebrew-tap"})
    # A token is not required for public repos, but using one when the workflow
    # provides it raises the rate limit from 60/hr to 1000/hr per repo.
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=60) as r:
        body = r.read()
    return body if raw else json.loads(body)


def latest_release() -> dict:
    return get(f"https://api.github.com/repos/{REPO}/releases/latest")


def checksums_for(release: dict) -> dict[str, str]:
    """Map archive filename to sha256, taken from the release's checksums.txt.

    The published checksums are authoritative. Rebuilding the archives locally
    and hashing those would be wrong: the builds are not byte-reproducible, so
    the hashes would not match what Homebrew actually downloads.
    """
    asset = next((a for a in release["assets"] if a["name"] == "checksums.txt"), None)
    if asset is None:
        raise SystemExit("release has no checksums.txt; refusing to guess hashes")
    sums = {}
    for line in get(asset["browser_download_url"], raw=True).decode().splitlines():
        line = line.strip()
        if not line:
            continue
        digest, name = line.split()
        sums[name] = digest
    return sums


def verify(release: dict, sums: dict[str, str], name: str) -> None:
    """Download one archive and confirm checksums.txt actually describes it.

    checksums.txt is just a text file in the release; nothing guarantees it
    matches the uploaded binaries. Publishing a cask whose hash is wrong breaks
    every install with a confusing checksum error, so one archive is verified
    end to end before anything is written.
    """
    asset = next((a for a in release["assets"] if a["name"] == name), None)
    if asset is None:
        raise SystemExit(f"release is missing {name}")
    got = hashlib.sha256(get(asset["browser_download_url"], raw=True)).hexdigest()
    if got != sums[name]:
        raise SystemExit(f"{name}: checksums.txt says {sums[name]}, archive hashes to {got}")


def description(tag: str) -> str:
    """Read the cask description out of greenlight's .goreleaser.yml at this tag.

    Keeping the single source of truth in the release repo is deliberate. The
    description drifted to Apple-only once already, while the scanner had
    supported Google Play for months.
    """
    url = f"https://raw.githubusercontent.com/{REPO}/{tag}/.goreleaser.yml"
    try:
        text = get(url, raw=True).decode()
    except (urllib.error.URLError, urllib.error.HTTPError):
        return FALLBACK_DESC
    m = re.search(r'^\s*description:\s*"([^"]+)"', text, re.M)
    return m.group(1) if m else FALLBACK_DESC


def render(version: str, sums: dict[str, str], desc: str) -> str:
    out = [
        "# This file was generated by GoReleaser. DO NOT EDIT.",
        'cask "greenlight" do',
        f'  version "{version}"',
        "",
    ]
    for os_block in ("on_macos", "on_linux"):
        out.append(f"  {os_block} do")
        for block, arch, suffix in TARGETS:
            if block != os_block:
                continue
            name = f"greenlight_{version}_{suffix}.tar.gz"
            out += [
                f"    {arch} do",
                f'      sha256 "{sums[name]}"',
                f'      url "https://github.com/{REPO}/releases/download/v#{{version}}/'
                f'greenlight_#{{version}}_{suffix}.tar.gz"',
                "    end",
            ]
        out += ["  end", ""]
    out += [
        '  name "greenlight"',
        f'  desc "{desc}"',
        f'  homepage "https://github.com/{REPO}"',
        "",
        "  livecheck do",
        '    skip "Auto-generated on release."',
        "  end",
        "",
        '  binary "greenlight"',
        "",
        "  postflight do",
        "    if OS.mac?",
        '      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", '
        '"#{staged_path}/greenlight"]',
        "    end",
        "  end",
        "",
        "  # No zap stanza required",
        "",
        "end",
    ]
    return "\n".join(out) + "\n"


def main() -> int:
    release = latest_release()
    tag = release["tag_name"]
    version = tag.lstrip("v")
    if release.get("draft") or release.get("prerelease"):
        print(f"{tag} is a draft or prerelease; nothing to do")
        return 0

    sums = checksums_for(release)
    missing = [
        f"greenlight_{version}_{s}.tar.gz"
        for *_, s in TARGETS
        if f"greenlight_{version}_{s}.tar.gz" not in sums
    ]
    if missing:
        raise SystemExit(f"checksums.txt is missing entries: {', '.join(missing)}")

    # Verify the arm64 mac archive, the one most people install.
    verify(release, sums, f"greenlight_{version}_darwin_arm64.tar.gz")

    new = render(version, sums, description(tag))
    old = CASK.read_text() if CASK.exists() else ""
    if new == old:
        print(f"cask already at {version}, no change")
        return 0

    CASK.parent.mkdir(parents=True, exist_ok=True)
    CASK.write_text(new)
    print(f"cask updated to {version}")
    # Signals the workflow to commit.
    if step_output := os.environ.get("GITHUB_OUTPUT"):
        Path(step_output).write_text(f"changed=true\nversion={version}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
